### ISSUE TITLE
Babel parser error 

### ISSUE THREAD

**Issue by sid-thakur** [agentcooper/react-pdf-highlighter#114]
Hello, I'm trying to compile the package react-pdf-highlighter and running into following issue. Any suggestion to fix will be very appreciated. Thanks!
```
react-pdf-highlighter\src\components\AreaHighlight.js: Unexpected token (9:12)

   7 | import "../style/AreaHighlight.css";
   8 | 
>  9 | import type { T_ViewportHighlight, T_LTWH } from "../types";     
     |             ^
  10 | 
  11 | type Props = {|
  12 |   highlight: T_ViewportHighlight,
at Parser._raise (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:748:17)
    at Parser.raiseWithData (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:741:17)        
    at Parser.raise (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:735:17)
    at Parser.unexpected (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:9101:16)
    at Parser.expectContextual (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:9067:41)    
    at Parser.parseImport (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:13102:12)        
    at Parser.parseStatementContent (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11776:27)
    at Parser.parseStatement (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11676:17)     
    at Parser.parseBlockOrModuleBlockBody (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:12258:25)
    at Parser.parseBlockBody (C:\Users\sidth\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:12249:10) {   
  loc: Position { line: 9, column: 12 },
  pos: 145,
  code: 'BABEL_PARSE_ERROR'
}
```

**Comment by agentcooper** [comment]
Please try version `5.1.0`.
