### ISSUE TITLE
node_modules\pdfjs-dist\legacy\web\pdf_viewer.js: symbol.charCodeAt is not a function

### ISSUE THREAD

**Issue by emsweet** [agentcooper/react-pdf-highlighter#234]
Does anyone have the same error?

 ERROR  Failed to compile with 1 errors                                                                                                    下午7:36:25
 error  in ./node_modules/pdfjs-dist/legacy/web/pdf_viewer.js

Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
TypeError: D:\project\ui-sms\client\node_modules\pdfjs-dist\legacy\web\pdf_viewer.js: symbol.charCodeAt is not a function
    at symbolToCodePoint (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:136625:22)
    at regenerate.add (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:137114:31)
    at Object.nested (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140193:23)
    at computeCharacterClass (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140403:20)
    at processCharacterClass (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140439:13)
    at processTerm (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140487:11)
    at D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140553:12
    at Array.map (<anonymous>)
    at processTerm (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140552:26)
    at D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140565:17
    at D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140009:15
    at Array.forEach (<anonymous>)
    at flatMap (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140008:8)
    at processTerm (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140564:16)
    at rewritePattern (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:140720:2)
    at PluginPass.RegExpLiteral (D:\project\ui-sms\client\node_modules\@umijs\deps\compiled\babel\bundle.js:18525:24)

**Comment by LuYangYang** [comment]
how did you fixed?
