### ISSUE TITLE
Project set-up error

### ISSUE THREAD

**Issue by sagnihotri773** [agentcooper/react-pdf-highlighter#80]
Project setup not working 

1. Download the git project.
2. npm install 
3. npm start 

Not working

**Comment by jsg2021** [comment]
That's not helpful. Any more details? It works for me.

**Comment by twtterence** [comment]
I cannot start the project on my Windows 10 environment also.

it prompts an error as popup:
![error](https://user-images.githubusercontent.com/10371354/92080382-10548880-edf4-11ea-8352-f669b3275334.png)

Here is the npm start error:
```
$ npm run start

> react-pdf-highlighter-monorepo@ start D:\react-pdf-highlighter\react-pdf-highlighter
> concurrently --kill-others 'npm run start:example' 'npm run start:react-pdf-highlighter'

[0] ''npm' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'run' is not recognized as an internal or external command,
[1] operable program or batch file.
[3] ''npm' is not recognized as an internal or external command,
[3] operable program or batch file.
[4] 'run' is not recognized as an internal or external command,
[4] operable program or batch file.
[4] run exited with code 1
--> Sending SIGTERM to other processes..
[3] 'npm exited with code 1
--> Sending SIGTERM to other processes..
[1] run exited with code 1
--> Sending SIGTERM to other processes..
[0] 'npm exited with code 1
--> Sending SIGTERM to other processes..
[2] start:example' exited with code 1
--> Sending SIGTERM to other processes..
[5] start:react-pdf-highlighter' exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-pdf-highlighter-monorepo@ start: `concurrently --kill-others 'npm run start:example' 'npm run start:react-pdf-highlighter'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-pdf-highlighter-monorepo@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(maskedname)\AppData\Roaming\npm-cache\_logs\2020-09-03T06_31_50_669Z-debug.log
```

Here is the debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-pdf-highlighter-monorepo@~prestart: react-pdf-highlighter-monorepo@
6 info lifecycle react-pdf-highlighter-monorepo@~start: react-pdf-highlighter-monorepo@
7 verbose lifecycle react-pdf-highlighter-monorepo@~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-pdf-highlighter-monorepo@~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\react-pdf-highlighter\react-pdf-highlighter\node_modules\.bin;C:\Users\(maskedname)\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\(maskedname)\bin;C:\Temp\Apps\SenchaCmd\bin\Sencha\Cmd\5.1.3.61;C:\Oracle\product\10.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Enterprise Vault\EVClient;C:\Program Files (x86)\Verint\Playback;C:\Program Files\NetIQ\SecureLogin\Win32;C:\Program Files\NetIQ\SecureLogin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files (x86)\PDFtk\bin;C:\Temp\Apps\ruby-2.2.6-x64-mingw32\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Temp\Apps\SenchaCmd\bin\Sencha\Cmd\5.1.3.61;C:\Oracle\product\10.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Enterprise Vault\EVClient;C:\Program Files (x86)\Verint\Playback;C:\Program Files\NetIQ\SecureLogin\Win32;C:\Program Files\NetIQ\SecureLogin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files\nodejs;C:\Program Files (x86)\PDFtk\bin;C:\Temp\Apps\ruby-2.2.6-x64-mingw32\bin;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Users\(maskedname)\AppData\Local\Microsoft\WindowsApps;C:\Temp\Java\jdk_8u201\bin;C:\Users\(maskedname)\AppData\Local\Programs\Fiddler;C:\Users\(maskedname)\.dotnet\tools;C:\Users\(maskedname)\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle react-pdf-highlighter-monorepo@~start: CWD: D:\react-pdf-highlighter\react-pdf-highlighter
10 silly lifecycle react-pdf-highlighter-monorepo@~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   "concurrently --kill-others 'npm run start:example' 'npm run start:react-pdf-highlighter'"
10 silly lifecycle ]
11 silly lifecycle react-pdf-highlighter-monorepo@~start: Returned: code: 1  signal: null
12 info lifecycle react-pdf-highlighter-monorepo@~start: Failed to exec start script
13 verbose stack Error: react-pdf-highlighter-monorepo@ start: `concurrently --kill-others 'npm run start:example' 'npm run start:react-pdf-highlighter'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid react-pdf-highlighter-monorepo@
15 verbose cwd D:\react-pdf-highlighter\react-pdf-highlighter
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error react-pdf-highlighter-monorepo@ start: `concurrently --kill-others 'npm run start:example' 'npm run start:react-pdf-highlighter'`
22 error Exit status 1
23 error Failed at the react-pdf-highlighter-monorepo@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by twtterence** [comment]
it works for me in version 2.2.0. But it doesn't work in 3.2.0.

**Comment by jsg2021** [comment]
Looks like the : in the arguments need quoting on windows. I use linux & macos for development. I can't speak for the author of this library, but I assume similar.

You can try using Windows Subsystem for Linux and run this in that environment, or you can test quoting the scripts in package.json and opening a PR.
